### ISSUE TITLE
US 01.01.01 - Mood event and user history

### ISSUE THREAD

**Issue by TaylorZowtuk** [CMPUT301F19T09/vibes#1]
#### Focus:
Moods

#### Partial User Story: 
As a participant, I want to add a mood event to my mood history, each event with the current date and time, a required emotional state, optional reason, and optional social situation.

#### Rationale: 
* To record a mood and its relevant details. 
* To save mood events in a collection for reviewing later.

#### Clarifications:
Q1: Regarding, "each event with the current date and time", should we allow the user to add an event for a non-current date and time. This would allow them to add events that happened in the past.

A1: Just current date and time.

Q2: Can a user edit the date and time of an event?

A2: No for now.

#### Story Points:
3

#### Risk Level:
Medium

#### Testing:
* Create a mood event without a reason and social situation.
* Create a mood event without a current date and time.
* Create a mood event with all fields and add to mood history.

**Comment by TaylorZowtuk** [comment]
Create two issues for this US: Mood Class and Add Fragment

**Comment by aktasfatih** [comment]
When you're storing the moods, store them under a collection called Moods and don't forget to store a property _posted_by_, which will have the username of who posted it. so it will be stored in both ways.

**Comment by TaylorZowtuk** [comment]
Responses to questions: 
A1. Just current date and time.
A2. No for now.

**Comment by TaylorZowtuk** [comment]
Complete as of PR #98.

Will need to be extended for allowing pulling gps location when adding mood event.
