### ISSUE TITLE
Searching functionality

### ISSUE THREAD

**Issue by TaylorZowtuk** [CMPUT301F19T09/vibes#109]
Functionality needs to be implemented for the search button. This functionality should allow the user to type in the name or parts of the names of users in the app and a list should appear with search results matching the inputted text. This functionality allows users to find other users in the app, to look at their profiles, and to request to follow (which is a required functionality).

**Comment by adriancleung** [comment]
Search implemented. Fields must be username, exact and case-sensitive.
