### ISSUE TITLE
Fix UI Constraint for Mood Details

### ISSUE THREAD

**Issue by adriancleung** [CMPUT301F19T09/vibes#111]

**Comment by TaylorZowtuk** [comment]
There are UI issues when using devices with smaller screens. For example, for long names the name will extend underneath the emotion picture.

**Comment by adriancleung** [comment]
Mood details show lots of empty space when photo is not present.

**Comment by adriancleung** [comment]
Photo constrained properly. Well done guyssssssss. #136
