### ISSUE TITLE
US 04.01.01 - Mood list

### ISSUE THREAD

**Issue by TaylorZowtuk** [CMPUT301F19T09/vibes#15]
#### Focus:
Mood History

#### Partial User Story:
As a participant, I want to view as a list my mood history, sorted by date and time, in reverse chronological order (most recent coming first).

#### Rationale:
* To view all moods in an organized place.
* To instantly see the latest moods a user has had.
* To display moods in a logical order.

#### Clarifications:
N/A

#### Story Points:
6

#### Risk Level:
High

#### Testing:
* Add moods with same dates and different times. View the list. Should be sorted with most recent time at top.
* Add moods with different dates and same times. View the list. Should be sorted with most recent date at top.

**Comment by graysongermsheid** [comment]
Completed as of #98 (See also #19)
