### ISSUE TITLE
US 04.02.01 - Mood history filter

### ISSUE THREAD

**Issue by TaylorZowtuk** [CMPUT301F19T09/vibes#16]
#### Focus:
Mood History

#### Partial User Story:
As a participant, I want to filter my mood history list to show only mood events with a particular emotional state.

#### Rationale:
* To view only relevant events when interested in looking at a particular mood.
* To control displayed information flexibly.

#### Clarifications:
N/A

#### Story Points:
1

#### Risk Level:
Low

#### Testing:
* Add various moods. Apply filter selecting a mood that is not in the mood history list. The list should be empty.
* Add a single mood. Apply filter selecting the mood matching the mood added. Nothing should change.
* Add various moods. Apply filter selecting a mood that is in the list multiple times. Those moods which match should remain and all others should be gone.

**Comment by aktasfatih** [comment]
The design is made. But, haven't been implemented yet.

**Comment by aktasfatih** [comment]
Sorry, not implemented.

**Comment by aktasfatih** [comment]
#f0c1ed3 it is done.
