### ISSUE TITLE
US 05.01.01 - Following another user

### ISSUE THREAD

**Issue by TaylorZowtuk** [CMPUT301F19T09/vibes#17]
#### Focus:
Mood Following and Sharing

#### Partial User Story:
As a participant, I want to ask another participant to follow their most recent mood event.

#### Rationale:
* To track the moods of other users you are interested in.
* To limit the amount of information you see about people you are following.
* To enforce users needing to ask for permission before being able to see another user's moods.

#### Clarifications:
Q1: What does following give access to? All the details of a mood or select things?

#### Story Points:
3

#### Risk Level:
Medium

#### Testing:
* Click the follow button on a different user's profile. The button should change to unfollow.
* Open a user's own profile. There should be no following button.

**Comment by adriancleung** [comment]
Accepting, and denying requests implemented. Currently, issues with following, requesting, and unfollowing other users. Backend database methods implement but frontend UI crashes.

**Comment by adriancleung** [comment]
Following, requesting, and unfollowing other users implemented with real-time updates. UI still having some issues

**Comment by adriancleung** [comment]
UI fixed, more testing needed before closing

**Comment by adriancleung** [comment]
IT FINALLY WORKS!!!! YAY! #144
