### ISSUE TITLE
US 05.02.01 - Handling follow requests

### ISSUE THREAD

**Issue by TaylorZowtuk** [CMPUT301F19T09/vibes#18]
#### Focus:
Mood Following and Sharing

#### Partial User Story:
As a participant, I want to grant another participant permission to follow my most recent mood event.

#### Rationale:
* To enforce users needing to ask for permission before being able to see another user's moods.
* To manage your follow requests.

#### Clarifications:
* Q1: If user A follows user B does that imply user B follows user A?
* Q2: Should a user be able to remove followers?

#### Story Points:
6

#### Risk Level:
Medium

#### Testing:
* Accept a user follow request; that user should be able to see your latest mood.
* Decline a user follow request; that user should not be able to see your latest mood.

**Comment by JoshSabet** [comment]
Completed as of PR #98
