### ISSUE TITLE
US 05.03.01 - Following list

### ISSUE THREAD

**Issue by TaylorZowtuk** [CMPUT301F19T09/vibes#19]
#### Focus:
Mood Following and Sharing

#### Partial User Story:
As a participant, I want to view as a list the most recent mood events of the other participants I am granted to follow, sorted by date and time, in reverse chronological order (most recent coming first).

#### Rationale:
* To track the moods of other users you are interested in.
* To compare how peoples most recent moods relate to each other and yourself.

#### Clarifications:
N/A

#### Story Points:
9

#### Risk Level:
High

#### Testing:
* Click the unfollow button on a different user's page that you are following currently. Open the 'following' view; the followed user's most recent mood should be gone.
* Click the follow button on a different user's profile. Open the 'following' view; the followed user's latest mood should appear.

**Comment by graysongermsheid** [comment]
Completed as of #98
