### ISSUE TITLE
US 01.02.01 - Mood emoticons and colors

### ISSUE THREAD

**Issue by TaylorZowtuk** [CMPUT301F19T09/vibes#2]
#### Focus:
Moods

#### Partial User Story:
As a participant, I want consistent emoticons and colors to depict and distinguish the emotional states in any view.

#### Rationale:
* Visualize moods at a glance.
* Distinguish moods.

#### Clarifications:
Q1: What is meant by 'consistent'. Is it a predefined set of emoticons and colors? Can one emoticon be assigned any color or are they 1-1? Does emotional state = a predefined emoticon and color? Do we let a user choose those combinations? Do they need to specify all of them or can it be a predefined set that they can customize? 

Q1.1: For the map of a person whose history you are following, do we see the person they're following's color emoticon combinations for a state, or is it the users.

#### Story Points:
2

#### Risk Level:
High

#### Testing:
* Create a mood and assign it an emoticon and color, does it keep its assigned emoticon and color between views.
* (Consistency test)

**Comment by JoshSabet** [comment]
Implement Parcible to MoodEvent

**Comment by JoshSabet** [comment]
Completed as of PR #98
