### ISSUE TITLE
US 06.01.01 - Add location for mood events

### ISSUE THREAD

**Issue by TaylorZowtuk** [CMPUT301F19T09/vibes#20]
#### Focus:
Geolocation and Maps

#### Partial User Story:
As a participant, I want to optionally attach my current location to a mood event.

#### Rationale:
* To track where a mood event occurred.
* To find patterns in mood events relating to location.
* Optional to allow privacy while still recording moods.

#### Clarifications:
Q1: Can the user edit the current location of a mood event? If we can edit an existing mood's location this should allow the user to specify where the event happened in the first place right?
A1: Yes. Get an initial fix (e.g., GPS), but it may require tweaking by the user.
Q2: "current location": what is the specificity wanted by this? City name? Coordinates?
A2: Coordinates, but the user should interact with a map.
Q3: Can we use an API to get/set location or should the user be providing the city or coordinates?
A3: Use built in GPS. Would prefer not to manually set.
Q4: Again can we use an API for displaying the map?
A4: Yes.

#### Story Points:
2

#### Risk Level:
Low

#### Testing:
* Attach a non-current location to a mood; should not allow (or should not be possible).
* Attach a current location to a mood event. Check the mood event details; the mood event should have the location added.

**Comment by TaylorZowtuk** [comment]
Responses to questions:
A1. Yes. Get an initial fix (e.g., GPS), but it may require tweaking by the user.
A2. Coordinates, but the user should interact with a map.
A3. Use built in GPS. Would prefer not to manually set.
A4. Yes.

**Comment by TaylorZowtuk** [comment]
Having a number of difficulties using API's. Trying to find a library which will handle location getting. 

https://github.com/android/location-samples

**Comment by TaylorZowtuk** [comment]
A possible library: https://github.com/yayaa/LocationManager

**Comment by TaylorZowtuk** [comment]
Location API issues resolved as of 532deb8445a7a7e0049b957a61e269880de7ec69

**Comment by adriancleung** [comment]
The location seems to be working. Can we close this issue?

**Comment by TaylorZowtuk** [comment]
Yes location was implemented successfully.
