### ISSUE TITLE
US 01.03.01 - View mood details

### ISSUE THREAD

**Issue by TaylorZowtuk** [CMPUT301F19T09/vibes#3]
#### Focus:
Moods

#### Partial User Story:
As a participant, I want to view a given mood event and all its available details.

#### Rationale:
* To review the circumstances of a mood.
* To understand some potential factors associated with certain mood events.

#### Clarifications:
N/A

#### Story Points:
1

#### Risk Level:
Low

#### Testing:
* Click on a mood and check if details are displayed.

**Comment by graysongermsheid** [comment]
Completed as of #98
