### ISSUE TITLE
Get user info from database and pass to profile fragment

### ISSUE THREAD

**Issue by davidherczeg** [CMPUT301F19T09/vibes#37]

**Comment by adriancleung** [comment]
Currently, requiring a delay of 4 seconds before rendering profile fragment after creating user object and requiring a delay of 3 seconds between loading user information from Firestore and profile image from Firebase Storage due to reference path stored in user information.

**Comment by adriancleung** [comment]
Issue no longer present. Implemented a callback listener to dynamically update user information in profile fragment.
