### ISSUE TITLE
US 02.03.01 - Restrict social situation input

### ISSUE THREAD

**Issue by TaylorZowtuk** [CMPUT301F19T09/vibes#8]
#### Focus:
Other Mood Details

#### Partial User Story:
As a participant, I want to specify the social situation for a mood event to be one of: alone, with one other person, with two to several people, or with a crowd.

#### Rationale:
* To provide context for physical environment during which a mood event occurred.
* To draw insights in how being with people effects moods.

#### Clarifications:
Q1: What kind of input do you want a user to provide here? A number? A string? If it is a number, what does "several people" mean? Would 2-7 people be an acceptable amount for that range and a crowd is 8+ people?
A1: Just a four option choice here. Leave it to the user to decide what "several" means.
Q2: Should the user be able to associate other users relating to the number of people in the social situation?
A2: Not sure of the question. These people might not be users of the app. (Follow up with this)

#### Story Points:
0.5

#### Risk Level:
Low

#### Testing:
* Create a mood even specifying each of the possible social situations and submit; each should be accepted.

**Comment by TaylorZowtuk** [comment]
Responses to questions:
A1. Just a four option choice here. Leave it to the user to decide what "several" means.
A2. Not sure of the question. These people might not be users of the app.

**Comment by adriancleung** [comment]
Fixed by @graysongermsheid #125
